### PR TITLE
Add MonadFail constraints for GHC 8.8 compatibility

### PR DESCRIPTION
**Pull request by akshaymankar**

### CODE REVIEW

**Comment by taruti** [comment]
Thanks for the PR!

Is there a reason you prefer to use `Either String` instead of `MonadFail`? Seems like `MonadFail` would be easier to integrate for users?

Sorry for the late reply. I'll get this sorted ASAP.

**Comment by akshaymankar** [comment]
I am using [multihash](https://hackage.haskell.org/package/multihash-0.1.2/docs/Data-Multihash-Base.html) which depends on `hex`. In the library, it expects `unhex` to return `Either String`. I think everyone who uses `unhex` would prefer to deal with the error in a pure way, so it would be nice if it returned `Either String`. So adding the `MonadFail` constraint is a breaking change too, so I thought the contract should be broken to be purer.

**Comment by taruti** [comment]
Hi, I'll merge this and add a `unhexM` and bump the version.

**Comment by taruti** [comment]
@akshaymankar Got a bumped version number out now. Thank you for your contribution!

**Pull request merged**
